### PR TITLE
Code & documentation improvements.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by longod** [comment]
Thanks for the PR.
This mod has not been released yet, and I think breaking changes will occur as it is still under personal development. So there may be a difference between comments and implementations.

**Comment by ghost** [comment]
> Thanks for the PR. This mod has not been released yet, and I think breaking changes will occur as it is still under personal development. So there may be a difference between comments and implementations.

That's good to know. The purpose was to document functions for myself and others who plan to contribute to the repository in the future. Good luck with the project as well.

**Review by ghost — COMMENTED** [review]
Majority of changes involve documentation improvements to LDoc but there are some other assertions that occur in the code that are much more accurate than the previous implementations.

**Comment by ghost** [comment]
Please openly communicate your changes next time.

**Pull request closed without merging**
